### ISSUE TITLE
webpack打包编译报错ERROR in path must be a string

### ISSUE THREAD

**Issue by wonyun** [steamerjs/steamer-react#32]
在项目的react-isomorphic-v0.1.0分支中，使用`npm run dev`开启本地服务时，webpack打包报错：

> ERROR in path must be a string

请指教？

环境：
mac： OS X EI Capitan
node:  5.10.0

**Comment by lcxfs1991** [comment]
能把报错的信息完整发出来吗？

**Comment by wonyun** [comment]
@lcxfs1991 没有完整信息，只是报了这个错误
> ERROR in path must be a string

![compile](https://cloud.githubusercontent.com/assets/4994497/26784584/0dc45dc6-4a31-11e7-89c4-3a497dae08e5.png)
<img width="415" alt="page" src="https://cloud.githubusercontent.com/assets/4994497/26784585/0dc7a152-4a31-11e7-98fb-b800c9473879.png">
